services:
  deepseek-free-api:
    container_name: deepseek-free-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    # # 如果想让 .env 配置文件生效，请取消下面两行的注释
    # env_file:
    #   - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data  # persist SQLite session DB across container restarts
